name: Publish Docker image
on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Pre-Release image
        if: "github.event.release.prerelease"
        run: |
          docker buildx build --no-cache --push \
            --tag shafr/mopidy-with-bt:${{ github.event.release.tag_name }} \
            --platform linux/arm/v7 .

      # - name: Build Release image
      #   if: "!github.event.release.prerelease"
      #   run: |
      #     docker buildx build --no-cache --push \
      #       --tag lolouk44/xiaomi-mi-scale:${{ github.event.release.tag_name }} \
      #       --tag lolouk44/xiaomi-mi-scale:latest \
      #       --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 .
      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}